# Generated by Django 3.0 on 2020-09-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='color',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='ripe',
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
